name: Output Info

on: [workflow_dispatch]

jobs:
  output-info:
    runs-on: ubuntu-latest
    steps:
      - name: Output Github Context
        run: echo "${{ toJson(github) }}"
      - name: Output runner Context 
        run: echo "${{ toJson(runner) }}"
